apimock:
    resource: "@ApimockBundle/Controller/"
    type:     annotation
    prefix:   /

cache:
    resource: "@CacheBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
